// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXGt7tMJ86aIXCWfVNYR_FXK8b1yNrxuo',
    appId: '1:685340923181:web:04c823a32d2a071c2f6fa4',
    messagingSenderId: '685340923181',
    projectId: 'babyshophub-5b7f1',
    authDomain: 'babyshophub-5b7f1.firebaseapp.com',
    storageBucket: 'babyshophub-5b7f1.firebasestorage.app',
    measurementId: 'G-ZYYND09TEQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGuk37DETrNQ1DxSMEO6-yKcNQTGPPp_4',
    appId: '1:685340923181:android:819330b3416c74122f6fa4',
    messagingSenderId: '685340923181',
    projectId: 'babyshophub-5b7f1',
    storageBucket: 'babyshophub-5b7f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPsrL3RQg3l0l8SAN4mWVOhMOvlkBm-jE',
    appId: '1:685340923181:ios:b880962c076764292f6fa4',
    messagingSenderId: '685340923181',
    projectId: 'babyshophub-5b7f1',
    storageBucket: 'babyshophub-5b7f1.firebasestorage.app',
    iosBundleId: 'com.example.babyshophub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPsrL3RQg3l0l8SAN4mWVOhMOvlkBm-jE',
    appId: '1:685340923181:ios:b880962c076764292f6fa4',
    messagingSenderId: '685340923181',
    projectId: 'babyshophub-5b7f1',
    storageBucket: 'babyshophub-5b7f1.firebasestorage.app',
    iosBundleId: 'com.example.babyshophub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXGt7tMJ86aIXCWfVNYR_FXK8b1yNrxuo',
    appId: '1:685340923181:web:058ae23e897370472f6fa4',
    messagingSenderId: '685340923181',
    projectId: 'babyshophub-5b7f1',
    authDomain: 'babyshophub-5b7f1.firebaseapp.com',
    storageBucket: 'babyshophub-5b7f1.firebasestorage.app',
    measurementId: 'G-CQ2DC4QEH9',
  );
}
